[tool.black]
line-length = 88
target-version = ["py39"]
include = '\.pyi?$'

[tool.ruff]
line-length = 88
target-version = "py39"
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "B",   # bugbear
    "W",   # pycodestyle warnings
    "C",   # mccabe complexity
    "N",   # naming
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "ANN", # annotations
    "RUF"  # ruff-specific rules
]
ignore = ["D203", "D213"]

[tool.ruff.isort]
known-first-party = ["common", "metrics"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"test_*.py" = ["D", "ANN"]

[tool.mypy]
python_version = "3.9"
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true